<a href="https://colab.research.google.com/github/WSzymczak23/projekty-SDA/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#VECTOR ARRAYS

In [ ]:
#%% import modules
import numpy as np

In [ ]:
ll = [1, 2, 3, 4, 5, 6]
v0 = np.array(ll)
print("v0={}".format(v0))

print(type(v0))            # Prints "<type 'numpy.ndarray'>"
print("v0 shape={}".format(v0.shape))
print(v0.dtype) # elements type

#%% vector creation
v1 = np.arange(1,10)
print("v1={}".format(v1))

v0=[1 2 3 4 5 6]
<class 'numpy.ndarray'>
v0 shape=(6,)
int64
v1=[1 2 3 4 5 6 7 8 9]


In [ ]:
#%%
v2 = np.arange(2,2.71,step=2)
sum = np.sum(v2)
print("sum={}".format(sum))

sum=10200


In [ ]:
x5=1.001
np.power(x5, 1000)

2.7169239322355936

In [ ]:
#%% dzieli na równe podzbiory
v3 = np.linspace(0,10,num=9)
print("v3={}".format(v3.shape))

v3=(9,)


In [ ]:
#%%
v3 = np.linspace(0,10,num=10,endpoint=False)
print("v3={}".format(v3))

v3=[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#%%
import numpy as np
v4 = np.linspace(2,2.70481382942,num=100,endpoint=True)
print("v4={}".format(v4))
#suma = sum(v4)
#print ("suma ciagu = {}".format(suma))

v4=[2.         2.00711933 2.01423866 2.02135799 2.02847733 2.03559666
 2.04271599 2.04983532 2.05695465 2.06407398 2.07119332 2.07831265
 2.08543198 2.09255131 2.09967064 2.10678997 2.11390931 2.12102864
 2.12814797 2.1352673  2.14238663 2.14950596 2.1566253  2.16374463
 2.17086396 2.17798329 2.18510262 2.19222195 2.19934129 2.20646062
 2.21357995 2.22069928 2.22781861 2.23493794 2.24205727 2.24917661
 2.25629594 2.26341527 2.2705346  2.27765393 2.28477326 2.2918926
 2.29901193 2.30613126 2.31325059 2.32036992 2.32748925 2.33460859
 2.34172792 2.34884725 2.35596658 2.36308591 2.37020524 2.37732458
 2.38444391 2.39156324 2.39868257 2.4058019  2.41292123 2.42004057
 2.4271599  2.43427923 2.44139856 2.44851789 2.45563722 2.46275655
 2.46987589 2.47699522 2.48411455 2.49123388 2.49835321 2.50547254
 2.51259188 2.51971121 2.52683054 2.53394987 2.5410692  2.54818853
 2.55530787 2.5624272  2.56954653 2.57666586 2.58378519 2.59090452
 2.59802386 2.60514319 2.61226252 2.61938185 2.62650118 2.63

In [ ]:
# check size == shape
print(v1.shape)
print(v2.shape)
print(v3.shape)
print(v4.shape)

(9,)
(18,)
(10,)
(11,)


In [ ]:
#%% matrix creation

a1 = np.array([1,2,3,4]) # Create a rank 1 array
print("a1={}".format(a1))
print(type(a1))            # Prints "<type 'numpy.ndarray'>"
print("a1 shape={}".format(a1.shape))
print(a1.dtype) # elements type

a1=[1 2 3 4]
<class 'numpy.ndarray'>
a1 shape=(4,)
int64


In [ ]:
#%%
a2 = np.array([ [1,2,3,4], [5,6,7,8] ])
print("a2={}".format(a2))
print("a2 shape={}".format(a2.shape))

a2=[[1 2 3 4]
 [5 6 7 8]]
a2 shape=(2, 4)


In [ ]:
#%%
a3 = np.zeros((4,2))      # Create an array of all zeros
print("a3={}".format(a3)) # Prints "[[ 0.  0.]
                          #          [ 0.  0.]]"


a3=[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#%%    
a4 = np.ones((3,2))       # Create an array of all ones
print("a4={}".format(a4)) 

a4=[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#%%
a5 = np.eye(5)        # Create a 2x2 identity matrix
print("a5={}".format(a5)) 


a5=[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# matrix with R=4 C=5 and 1 on diagnol
# below main diagnol
a = np.eye(4, 5, k = -3)
print("\nMatrix a : \n", a)


Matrix a : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [ ]:
#%% 
a6 = np.random.random((10,10)) # Create an array filled with random values
print("a6={}".format(a6))    # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

a6=[[0.61785776 0.69733483 0.94486125 0.39516468 0.85230068 0.08843073
  0.71509158 0.56309789 0.66476971 0.73826528]
 [0.44556939 0.89482035 0.43936519 0.70981815 0.48692117 0.95379844
  0.40281302 0.63744095 0.1079289  0.33998285]
 [0.95116673 0.92816692 0.53030048 0.39582924 0.80073315 0.67801687
  0.55721402 0.91464475 0.01649249 0.35322642]
 [0.53090928 0.89320422 0.64557159 0.93947829 0.24160775 0.12630248
  0.0324661  0.20760938 0.65295086 0.16131539]
 [0.5435457  0.08267851 0.80786189 0.34885974 0.55245523 0.59318325
  0.09218903 0.31169939 0.09169429 0.890232  ]
 [0.75868833 0.92313987 0.68186244 0.07661366 0.16372315 0.86560008
  0.91359314 0.76947707 0.35491933 0.44153292]
 [0.37103161 0.83904865 0.28297419 0.60623463 0.83794075 0.63988935
  0.88777791 0.33392935 0.88180339 0.53110219]
 [0.81639448 0.37631455 0.26396647 0.64665631 0.78415226 0.44468471
  0.2067345  0.3693022  0.3191577  0.10096242]
 [0.31613157 0.1456749  0.08636996 0.0796396  0.48851813 0.63945377
  0.70535

In [ ]:
#%%
a7 = np.full((5,6), 100)  # Create a constant array
print("a7={}".format(a7)) 


a7=[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]


In [ ]:
#%% 3d arrays, wgrrrrrrr!
b1 = np.array([ 
                [ [1, 2,3], [3, 4,5], [5, 6,7] , [5, 6,7] ],
                [ [11, 12, 13], [13, 14, 15], [15, 16, 17], [5, 6,7]  ],
                [ [21, 22, 23], [23, 24, 25], [25, 26, 27], [5, 6,7]  ],
                [ [31, 32, 33], [33, 34, 35], [35, 36, 37] , [5, 6,7] ],
                [ [31, 32, 33], [33, 34, 35], [35, 36, 37] , [5, 6,7] ]
              ])

# 
#                 axis2=2
#                ___________ 
#              /     /     /|     
#   axis1=3   /     /     / |
#            /_____/_____/  |
#           |            |  |
#           |            |  | 
# axis0=4   |            |  /
#           |            | /
#           |____________|/

print("b1={}".format(b1))
print("b1 shape={}".format(b1.shape))


b1=[[[ 1  2  3]
  [ 3  4  5]
  [ 5  6  7]
  [ 5  6  7]]

 [[11 12 13]
  [13 14 15]
  [15 16 17]
  [ 5  6  7]]

 [[21 22 23]
  [23 24 25]
  [25 26 27]
  [ 5  6  7]]

 [[31 32 33]
  [33 34 35]
  [35 36 37]
  [ 5  6  7]]

 [[31 32 33]
  [33 34 35]
  [35 36 37]
  [ 5  6  7]]]
b1 shape=(5, 4, 3)


In [ ]:
#%% help me, my brain is melting
print(b1[0,:,:].shape)
print(b1[0,:,:])

#%%
print(b1[:,2,:].shape)
print(b1[:,2,:])
#%%
print(b1[1,2,0].shape)
print(b1[1,2,0])

# play with indexes

# 5,2,3

# %%

(4, 3)
[[1 2 3]
 [3 4 5]
 [5 6 7]
 [5 6 7]]
(5, 3)
[[ 5  6  7]
 [15 16 17]
 [25 26 27]
 [35 36 37]
 [35 36 37]]
()
15


In [ ]:
#MATRIX ELEMENT ACCESS

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a[2, 3])   # Prints "2"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12


In [ ]:
#%%

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)
c = a[:2]
print(c)
d= c[:,1:3]
print(d)

[[2 3]
 [6 7]]
[[1 2 3 4]
 [5 6 7 8]]
[[2 3]
 [6 7]]


In [ ]:
#%% A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print( a[0, 1])   # Prints "77"

77
77


In [ ]:
#%% Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [ ]:
#%% We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                            #          [ 6]
                            #          [10]] (3, 1)"

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
#%% Integer array indexing: 

a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b = np.array([[1,2],[3,4],[5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 1]])  # Prints "[1 4 5]"

[1 4 6]


In [ ]:
# The above example of integer array indexing is equivalent to this:
print( np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

[1 4 5]


In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print( a[[0, 1], [1, 1]])  # Prints "[2 2]"

[2 4]


In [ ]:
# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"       

[2 2]


In [ ]:
#%%  Create a new array from which we will select elements
a = np.array([[1,2,3,4,5], [6,7,8, 9, 10], [11,12,13,14,15], [16, 17, 18, 19, 20], [21,22,23,24,25]])

print(a)  # prints "array([[ 1,  2,  3],
         #                [ 4,  5,  6],
         #                [ 7,  8,  9],
         #                [10, 11, 12]])"

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

In [ ]:
# Select one element from each row of a using the indices in b
print( a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  8 11 17]


In [ ]:
#%% Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print( a)  # prints "array([[11,  2,  3],
         #                [ 4,  5, 16],
         #                [17,  8,  9],
         #                [10, 21, 12]])

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
#Boolean array indexing         

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print( bool_idx)      # Prints "[[False False]
                    #          [ True  True]
                    #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [ ]:
#MATH in matrixes

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
print( x.dtype)         # Prints "int64"

x = np.array([1., 2.])  # Let numpy choose the datatype
print( x.dtype)             # Prints "float64"

x = np.array([1, 127], dtype=np.int8)  # Force a particular datatype
print(x.dtype)       

#%%
x = np.array([1, 128], dtype=np.int8)  # Force a particular datatype
print(x)       

int64
float64
int8
[   1 -128]


In [ ]:
#%% basic math operation
x = np.array([[1,2],[3,4], [5,6]], dtype=np.float64)
y = np.array([[5,6, 1], [8,9,1]], dtype=np.float64)
print(x.shape)
print(y.shape)

(3, 2)
(2, 3)


In [ ]:
#%% Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [ 4.  5.]
 [13. 15.]]
[[ 6.  8.]
 [ 4.  5.]
 [13. 15.]]


In [ ]:
#%% Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)

print(np.subtract(x, y))

[[-4. -4.]
 [ 2.  3.]
 [-3. -3.]]
[[-4. -4.]
 [ 2.  3.]
 [-3. -3.]]


In [ ]:
print(x) #3x2


[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
print(y) #2x3

[[5. 6. 1.]
 [8. 9. 1.]]


In [ ]:
#%% Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(np.dot(x, y))


[[21. 24.  3.]
 [47. 54.  7.]
 [73. 84. 11.]]


In [ ]:
#%% Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
#%% 
# list of math functions https://numpy.org/doc/stable/reference/routines.math.html

#%% Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print( np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
#%% vector matrix operation
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])

In [ ]:
#%% Inner product of vectors; both produce 219
print( v.dot(w))
print( np.dot(v, w))

219
219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.shape)
print(v.shape)
print(x.dot(v))
print(np.dot(x, v))


(2, 2)
(2,)
[29 67]
[29 67]


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
#%%
x = np.array([[1,2],[3,4]])

print(x)
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))# Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [ ]:
#%%
print(np.mean(x))  # Compute mean of all elements;
print(np.mean(x, axis=0))# Compute mean of each column;
print(np.mean(x, axis=1))  # Compute mean of each row; 

2.5
[2. 3.]
[1.5 3.5]


In [ ]:
#%%
print(np.std(x))          # Compute standard derivation of all elements;
print(np.std(x, axis=0))  # Compute standard derivation of each column;
print(np.std(x, axis=1))  # Compute standard derivation of each row; 

1.118033988749895
[1. 1.]
[0.5 0.5]


In [ ]:
#%%
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
           #          [3 4]]"
print(x.T)  # Prints "[[1 3]
           #          [2 4]]"


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
#%% Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)  # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[1 2 3]
[1 2 3]


In [ ]:
# generate linear map from (-pi/2, pi/2)
x = np.linspace(-np.pi/2,np.pi/2,10)

# calculate sine and cosine in one step, for whole array
print(np.sin(x))

print(np.cos(x))

[-1.         -0.93969262 -0.76604444 -0.5        -0.17364818  0.17364818
  0.5         0.76604444  0.93969262  1.        ]
[6.12323400e-17 3.42020143e-01 6.42787610e-01 8.66025404e-01
 9.84807753e-01 9.84807753e-01 8.66025404e-01 6.42787610e-01
 3.42020143e-01 6.12323400e-17]


In [ ]:
# [-5, ... , 5]
x = np.arange(-5,5)

#%% calcultae e^(-5), .... , e^5
print(np.exp(x))

#%% x^2, compute x to power of 2 
print(np.power(x,2))

# using python operators compute each element of matrix x to power of 2
print(x**2)

# calculate 2^-5 ... 2^5, !!! error, integer not allowed negative exponent
#print(np.power(2,x))

# now everything works as expected :)
x = np.arange(-5,5, dtype=np.float)

[6.73794700e-03 1.83156389e-02 4.97870684e-02 1.35335283e-01
 3.67879441e-01 1.00000000e+00 2.71828183e+00 7.38905610e+00
 2.00855369e+01 5.45981500e+01]
[25 16  9  4  1  0  1  4  9 16]
[25 16  9  4  1  0  1  4  9 16]


In [ ]:
# natural logarithm, look at minus values!!
print(np.log(x))

xx = np.power(2,x)
print(xx)

# logarithm base 2
print(np.log2(xx))

[       nan        nan        nan        nan        nan       -inf
 0.         0.69314718 1.09861229 1.38629436]
[ 0.03125  0.0625   0.125    0.25     0.5      1.       2.       4.
  8.      16.     ]
[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


In [ ]:
#Matrix manipulation

In [ ]:
#%%
a1 = np.arange(0,24,step=1)
print(a1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
#%%
# reshape matrix a1 into (2,12) matrix, 
a2 = np.reshape(a1,(3,8))
print(a2)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [ ]:
#%%
a1[0] = 12345
print(a2)
# assing correct value as was before
a1[0] = 0

[[12345     1     2     3     4     5     6     7]
 [    8     9    10    11    12    13    14    15]
 [   16    17    18    19    20    21    22    23]]


In [ ]:
#%%
a3 = np.reshape(a2,(3,8))
print(a3)
a4 = np.reshape(a2,(4,6))
print(a4)
a5 = np.reshape(a2,(6,4))
print(a5)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:

#%% resize - https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.resize.html#numpy.resize
# compare with reshape :)


a1 = np.ones((3,3))
a2 = np.ones((8,3))*2
a3 = np.ones((3,7))*1000

In [ ]:
print(a1)
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
# Join a sequence of arrays along an existing axis
# https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html#numpy.concatenate
np.concatenate((a1,a2), axis=0)

# ValueError: all the input array dimensions except for the concatenation axis must match exactly
# np.concatenate((a1,a3))

np.concatenate((a1,a3), axis=1)

array([[   1.,    1.,    1., 1000., 1000., 1000., 1000., 1000., 1000.,
        1000.],
       [   1.,    1.,    1., 1000., 1000., 1000., 1000., 1000., 1000.,
        1000.],
       [   1.,    1.,    1., 1000., 1000., 1000., 1000., 1000., 1000.,
        1000.]])

In [ ]:
#%% stack - Join a sequence of arrays along a new axis.
#  https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.stack.html#numpy.stack

v1 = np.arange(1,5)
v2 = np.arange(5,9)
print(v1)
print(v2)

#%%
vv = np.stack((v1,v2),axis=0)
vh = np.stack((v1,v2),axis=1)
print(vv)
print(vh)
print(vh.T)

[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#%% stack in 3d
a = np.reshape(np.arange(1,9),(2,4))
b = np.reshape(np.arange(1,9),(2,4))+10
print(a)
print(b)
#%%
# one matrix on top of another
#    ___________
#   /          /
#  /          /
# /__________/
#    ___________
#   /          /
#  /          /
# /__________/

ab0 = np.stack((a,b),axis=0)
print(ab0)
print(ab0.shape)
print(ab0[0,:,:])

[[1 2 3 4]
 [5 6 7 8]]
[[11 12 13 14]
 [15 16 17 18]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
(2, 2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#%% one matrix behind another
#         ____________
#        |            |
#  ______|_____       |
# |            |      |
# |            |______|
# |            |
# |____________|

ab1 = np.stack((a,b),axis=1)
print(ab1)
print(ab1.shape)
print(ab1[0,:,:])

[[[ 1  2  3  4]
  [11 12 13 14]]

 [[ 5  6  7  8]
  [15 16 17 18]]]
(2, 2, 4)
[[ 1  2  3  4]
 [11 12 13 14]]


In [ ]:
#%% one matrix next to another
#
#    /|    /|
#   / |   / |
#  /  |  /  |
# |   | |   |
# |  /  |  /
# | /   | /
# |/    |/

ab2 = np.stack((a,b),axis=2)
print(ab2)
print(ab2.shape)
print(ab2[0,:,:])

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]
  [ 8 18]]]
(2, 4, 2)
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]]


In [ ]:
#%% Split an array into multiple sub-arrays. https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.split.html#numpy.split

x = np.arange(15)
xs= np.split(x, 5)
print(xs)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11]), array([12, 13, 14])]


In [ ]:
#%% split an array on those indexes
x = np.arange(15)
xs = np.split(x, [3, 5, 6, 10])
print(xs)

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8, 9]), array([10, 11, 12, 13, 14])]


In [ ]:
#%% Tile
b = np.array([0, 1, 2])
print(np.tile(b, 4))

[0 1 2 0 1 2 0 1 2 0 1 2]


In [ ]:
#%% tile 2x2
#       |
# ------|------
#       |
print(np.tile(b, (4, 2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [ ]:
#%%
c = np.array([ [0, 1, 2], [3, 4, 5] ])
print(c)
print(np.tile(c,3))

[[0 1 2]
 [3 4 5]]
[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]


In [ ]:
#Vector, matrix broadcasting

In [ ]:
#%% We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

#%% Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
#%% We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
#%%
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4]
         #          [ 5  5  7]
         #          [ 8  8 10]
         #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
#%% We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
         #          [ 5  5  7]
         #          [ 8  8 10]
         #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
#%% Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
#%% Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

[[2 2 4]
 [5 5 7]]


In [ ]:
print(x)
print(x.T)
print(w)
print(w.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[11 12]
[11 12]


In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[12 13 14]
 [16 17 18]]
[[12 13 14]
 [16 17 18]]


In [ ]:
#%% Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
#Utility functions

In [ ]:
#%% sorting
a = np.array([[1,4],[3,1]])
print(a)
np.sort(a)  # sort along the last axis

#%%
np.sort(a, axis=None)     # sort the flattened array
#%%
np.sort(a, axis=1)  # sort along the first axis

[[1 4]
 [3 1]]


array([[1, 4],
       [1, 3]])

In [ ]:
#%% argsort

x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

In [ ]:
#%%

x = np.array([[0, 3], [2, 2]])
print(x)
ind = np.argsort(x, axis=0)  # sorts along first axis (down)
ind


np.take_along_axis(x, ind, axis=0)  # same as np.sort(x, axis=0)


[[0 3]
 [2 2]]


array([[0, 2],
       [2, 3]])

In [ ]:
#%%

a = np.arange(6).reshape(2,3) + 10

#%%
np.argmax(a)

np.argmax(a, axis=0)

np.argmax(a, axis=1)

array([2, 2])