<a href="https://colab.research.google.com/github/WSzymczak23/projekty-SDA/blob/main/Overview_of_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Spis treści<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Sesja-TensorFlow" data-toc-modified-id="Sesja-TensorFlow-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Sesja TensorFlow</a></span></li><li><span><a href="#Stałe" data-toc-modified-id="Stałe-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Stałe</a></span></li><li><span><a href="#Operacje" data-toc-modified-id="Operacje-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Operacje</a></span></li><li><span><a href="#Węzły-zastępcze" data-toc-modified-id="Węzły zastępcze-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Węzły zastępcze</a></span></li><li><span><a href="#Tworzenie-tensorów-z-istniejących-obiektów" data-toc-modified-id="Tworzenie-tensorów-z-istniejących-obiektów-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Tworzenie tensorów z istniejących obiektów</a></span><ul class="toc-item"><li><span><a href="#Tensory-zerowego-rzędu-(skalary)" data-toc-modified-id="Tensory-zerowego-rzędu-(skalary)-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Tensory zerowego rzędu (skalary)</a></span></li><li><span><a href="#Tensory-1.-rzędu-(wektory)" data-toc-modified-id="Tensory-1.-rzędu-(wektory)-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Tensory 1. rzędu (wektory)</a></span></li><li><span><a href="#Tensory-2.-rzędu-(macierze)" data-toc-modified-id="Tensory-2.-rzędu-(macierze)-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Tensory 2. rzędu (macierze)</a></span></li><li><span><a href="#Tensory-3.-rzędu" data-toc-modified-id="Tensory-3.-rzędu-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Tensory 3. rzędu</a></span></li></ul></li><li><span><a href="#Zmienne" data-toc-modified-id="Zmienne-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Zmienne</a></span></li><li><span><a href="#Tworzenie-tensorów-z-funkcji-bibliotecznych" data-toc-modified-id="Tworzenie-tensorów-z-funkcji-bibliotecznych-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Tworzenie tensorów z funkcji bibliotecznych</a></span></li><li><span><a href="#Zamknięcie-sesji-interaktywnej" data-toc-modified-id="Zamknięcie-sesji-interaktywnej-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Zamknięcie sesji interaktywnej</a></span></li><li><span><a href="#Grafy-obliczeniowe" data-toc-modified-id="Grafy-obliczeniowe-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Grafy obliczeniowe</a></span><ul class="toc-item"><li><span><a href="#Budowa-i-uruchomienie-prostego-grafu-obliczeniowego" data-toc-modified-id="Budowa-i-uruchomienie-prostego-grafu-obliczeniowego-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Budowa i uruchomienie prostego grafu obliczeniowego</a></span></li><li><span><a href="#Graf-na-urządzeniach-obliczeniowych" data-toc-modified-id="Graf-na-urządzeniach-obliczeniowych-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Graf na urządzeniach obliczeniowych</a></span><ul class="toc-item"><li><span><a href="#Lista-dostępnych-urządzeń" data-toc-modified-id="Lista-dostępnych-urządzeń-9.2.1"><span class="toc-item-num">9.2.1&nbsp;&nbsp;</span>Lista dostępnych urządzeń</a></span></li><li><span><a href="#Domyślne-rozmieszczenie" data-toc-modified-id="Domyślne-rozmieszczenie-9.2.2"><span class="toc-item-num">9.2.2&nbsp;&nbsp;</span>Domyślne rozmieszczenie</a></span></li><li><span><a href="#Rozmieszczanie-na-CPU" data-toc-modified-id="Rozmieszczanie-na-CPU-9.2.3"><span class="toc-item-num">9.2.3&nbsp;&nbsp;</span>Rozmieszczanie na CPU</a></span></li><li><span><a href="#Rozmieszczanie-na-CPU-i-GPU" data-toc-modified-id="Rozmieszczanie-na-CPU-i-GPU-9.2.4"><span class="toc-item-num">9.2.4&nbsp;&nbsp;</span>Rozmieszczanie na CPU i GPU</a></span></li></ul></li><li><span><a href="#Wykonywanie-grafu-g-jako-domyślnego" data-toc-modified-id="Wykonywanie-grafu-g-jako-domyślnego-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>Wykonywanie grafu g jako domyślnego</a></span></li></ul></li><li><span><a href="#Regresja-logistyczna-z-TensorFlow" data-toc-modified-id="Regresja-logistyczna-z-TensorFlow-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Regresja logistyczna z TensorFlow</a></span></li><li><span><a href="#Regresja-logistyczna-z-Keras" data-toc-modified-id="Regresja-logistyczna-z-Keras-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Regresja logistyczna z Keras</a></span></li></ul></div>

# TensorFlow 101 <a class="tocSkip">

In [ ]:
!pip install tensorflow==1.14
import tensorflow as tf
print(tf.__version__)
import numpy as np
print('Wersja Numpy :',np.__version__)
import sys
print('Interpreter Pythona i wersja:',sys.version)

     |████████████████████████████████| 109.3MB 91kB/s 
     |████████████████████████████████| 491kB 8.7MB/s 
     |████████████████████████████████| 3.2MB 16.4MB/s 
     |████████████████████████████████| 51kB 6.6MB/s 
ERROR: kapre 0.3.5 has requirement tensorflow>=2.0.0, but you'll have tensorflow 1.14.0 which is incompatible.
  Found existing installation: tensorflow-estimator 2.5.0
    Uninstalling tensorflow-estimator-2.5.0:
      Successfully uninstalled tensorflow-estimator-2.5.0
  Found existing installation: tensorboard 2.5.0
    Uninstalling tensorboard-2.5.0:
      Successfully uninstalled tensorboard-2.5.0
  Found existing installation: tensorflow 2.5.0
    Uninstalling tensorflow-2.5.0:
      Successfully uninstalled tensorflow-2.5.0


/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

1.14.0
Wersja Numpy : 1.19.5
Interpreter Pythona i wersja: 3.7.10 (default, May  3 2021, 02:48:31) 
[GCC 7.5.0]


/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWa

# Sesja TensorFlow 

In [ ]:
#sesje tylko w tf1
tfs = tf.Session()

In [ ]:
hello = tf.constant("Witamy na zajeciach z tensorflow!!")
print(tfs.run(hello))

b'Witamy na zajeciach z tensorflow!!'


# Stałe

In [ ]:
const1 = tf.constant(34, name='x')
const2 = tf.constant(59.0, name='y')
const3 = tf.constant(32.0, dtype=tf.float64, name='z')
print('const1 (x): ', const1)
print('const2 (y): ', const2)
print('const3 (z): ', const3)

const1 (x):  Tensor("x:0", shape=(), dtype=int32)
const2 (y):  Tensor("y:0", shape=(), dtype=float32)
const3 (z):  Tensor("z:0", shape=(), dtype=float64)


In [ ]:
#Aby wyswietlić wynik  w postaci liczbowej a nie w postaci obiektu tensorflow nalezy używać tfs.run - korzystamy wtedy z konkretnej sesji tensorflow
print('run([const1,const2,const3]) : ', tfs.run([const1, const2, const3]))

run([const1,const2,const3]) :  [34, 59.0, 32.0]


In [ ]:
#deklaracja zer
a = tf.zeros(2)
tfs.run(a)

array([0., 0.], dtype=float32)

In [ ]:
#deklaracja jedynek
b = tf.ones(4)
tfs.run(b)

array([1., 1., 1., 1.], dtype=float32)

In [ ]:
#Zadania
#1. Stworz 6 stalych kazda innego typu (int, float).
#2* Stworz tensor 2D skladajacy sie ze stałych ktore są tylko 5-kami

In [ ]:
a=tf.random_normal((10,10), mean=0, stddev=1)
tfs.run(a)

array([[-0.10223877,  1.3842531 ,  0.5269022 , -1.0756168 , -0.5146406 ,
        -0.3104371 ,  0.46688405,  0.27272692, -0.50712264, -0.8856756 ],
       [ 0.5205834 , -0.18120657, -1.0938598 , -0.01137738, -1.4780076 ,
        -0.6715659 , -0.3574379 ,  0.4236595 ,  0.13869329,  0.4188256 ],
       [-0.03807225,  0.63436455,  0.16781159, -2.6208034 , -0.00967516,
        -1.0312852 ,  0.77811146,  0.42835227,  0.3216789 ,  0.53164345],
       [-0.76785207, -0.69724804,  0.28274772,  1.0907676 , -1.4323065 ,
         0.75436467,  0.38340288, -1.357182  ,  1.9016689 , -0.48499444],
       [-0.16062067, -1.5728891 ,  0.04403835, -0.2762578 , -1.1845266 ,
         0.06508821, -1.0126586 ,  0.1171057 ,  0.19370857,  0.2669653 ],
       [-0.40106958,  0.75728685,  0.28979835, -0.293418  ,  0.39237243,
        -0.86068773, -1.3868742 ,  0.09064666,  2.0622637 , -0.06395718],
       [-0.091501  ,  1.1955789 , -0.67597604, -0.45298567, -0.10434926,
        -0.99653786,  0.28382203,  0.86408883

# Operacje

In [ ]:
op1 = tf.add(const2, const3)
op2 = tf.multiply(const2, const3)
print('op1 : ', op1)
print('op2 : ', op2)

op1 :  Tensor("Add_2:0", shape=(), dtype=float32)
op2 :  Tensor("Mul_2:0", shape=(), dtype=float32)


In [ ]:
print('run(op1) : ', tfs.run(op1))
print('run(op2) : ', tfs.run(op2))

run(op1) :  91.0
run(op2) :  1888.0


# Węzły zastępcze

In [ ]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print('p1 : ', p1)
print('p2 : ', p2)

p1 :  Tensor("Placeholder:0", dtype=float32)
p2 :  Tensor("Placeholder_1:0", dtype=float32)


In [ ]:
mult_op = p1 * p2  # skrót dla tf.multiply(p1, p2)

In [ ]:
print('run(mult_op,{p1:13.4, p2:61.7}) : ',tfs.run(mult_op,{p1:13.4, p2:61.7}))

run(mult_op,{p1:13.4, p2:61.7}) :  826.77997


In [ ]:
feed_dict={p1: 15.4, p2: 19.5}
print('run(mult_op,feed_dict = {p1:15.4, p2:19.5}) : ',
      tfs.run(mult_op, feed_dict=feed_dict))

run(mult_op,feed_dict = {p1:15.4, p2:19.5}) :  300.3


In [ ]:
feed_dict={p1: [2.0, 3.0, 4.0], p2: [3.0, 4.0, 5.0]}
print('run(mult_op,feed_dict={p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}):',
      tfs.run(mult_op, feed_dict=feed_dict))

run(mult_op,feed_dict={p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}): [ 6. 12. 20.]


In [ ]:
#Stworzyć feed dict w formie klucz : 10 elementowy wektor, 2-3 wektory. Przemnożyć każdy element przez każdy. 
#Zsumować ich wartości

## Tensory zerowego rzędu (skalary)

In [ ]:
tf_t = tf.convert_to_tensor(5, dtype=tf.int32)

print('tf_t : ', tf_t)
print('run(tf_t) : \n', tfs.run(tf_t))

tf_t :  Tensor("Const_6:0", shape=(), dtype=int32)
run(tf_t) : 
 5


## Tensory 1. rzędu (wektory)

In [ ]:
a1dim = np.array([1, 2, 3, 4, 5.99])
print('Kształt a1dim : ', a1dim.shape)

tf_t = tf.convert_to_tensor(a1dim)

print('tf_t : ', tf_t)
print('tf_t[0] : ', tf_t[0])
print('tf_t[2] : ', tfs.run(tf_t[2]))
#print('run(tf_t) : \n', tfs.run(tf_t))

Kształt a1dim :  (5,)
tf_t :  Tensor("Const_2:0", shape=(5,), dtype=float64)
tf_t[0] :  Tensor("strided_slice:0", shape=(), dtype=float64)
tf_t[2] :  3.0


## Tensory 2. rzędu (macierze)

In [ ]:
tfs = tf.Session()
a2dim = np.array([(1, 2, 3, 4, 5.99),
                  (2, 3, 4, 5, 6.99),
                  (3, 4, 5, 6, 7.99)
                  ])
print('Kształt a2dim : ', a2dim.shape)

tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0] : ', tf_t[0][0])
print('tf_t[1][2] : ', tf_t[1][2])
print('run(tf_t) : \n', tfs.run(tf_t[2][4]))

Kształt a2dim :  (3, 5)
tf_t :  Tensor("Const_9:0", shape=(3, 5), dtype=float64)
tf_t[0][0] :  Tensor("strided_slice_19:0", shape=(), dtype=float64)
tf_t[1][2] :  Tensor("strided_slice_21:0", shape=(), dtype=float64)
run(tf_t) : 
 7.99


## Tensory 3. rzędu

In [ ]:
a3dim = np.array([[[1, 2],
                   [3, 4]
                   ],
                  [[5, 6],
                   [7, 8]
                   ]
                  ])
print('Kształt a3dim : ', a3dim.shape)

tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0][0] : ', tf_t[0][0][0])
print('tf_t[1][1][1] : ', tf_t[1][1][1])
print('run(tf_t) : \n', tfs.run(tf_t[1][1][1]))
print('run(tf_t) : \n', tfs.run(tf_t))

Kształt a3dim :  (2, 2, 2)
tf_t :  Tensor("Const_9:0", shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0] :  Tensor("strided_slice_13:0", shape=(), dtype=float64)
tf_t[1][1][1] :  Tensor("strided_slice_16:0", shape=(), dtype=float64)
run(tf_t) : 
 8.0
run(tf_t) : 
 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


In [ ]:
a3dim = np.array([[[1, 2],
                   [3, 4]
                   ],
                  [[5, 6],
                   [7, 8]
                   ]
                  ])
print('Kształt a3dim : ', a3dim.shape)

tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0][0] : ', tf_t[0][0][0])
print('tf_t[1][1][1] : ', tf_t[1][1][1])
print('run(tf_t) : \n', tfs.run(tf_t))

Kształt a3dim :  (2, 2, 2)
tf_t :  Tensor("Const_10:0", shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0] :  Tensor("strided_slice_22:0", shape=(), dtype=float64)
tf_t[1][1][1] :  Tensor("strided_slice_25:0", shape=(), dtype=float64)
run(tf_t) : 
 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


# Zmienne

In [ ]:
# Model liniowy y = w * x + b
# Definiowanie parametrów modelu ale też definiowanie zmiennej
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Definiowanie wejścia i wyjścia modelu
x = tf.placeholder(tf.float32)
y = w * x + b

print('w:', w)
print('x:', x)
print('b:', b)
print('y:', y)

w: <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
x: Tensor("Placeholder_2:0", dtype=float32)
b: <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>
y: Tensor("add:0", dtype=float32)


In [ ]:
# Inicjacja i wydruk zmiennej y
tfs.run(tf.global_variables_initializer())
print('run(y,{x:[1,2,3,4]}) : ', tfs.run(y, {x: [1, 2, 3, 4]}))

run(y,{x:[1,2,3,4]}) :  [0.         0.3        0.6        0.90000004]


In [ ]:
#var1 = tf.Variable(3.,dtype=tf.float64, name="var1")
var1 = tf.get_variable(initializer=tf.constant_initializer(3.), dtype=tf.float64, name="var1", shape=())
current_scope = tf.contrib.framework.get_name_scope()
print(var1.name)
with tf.variable_scope(current_scope, reuse=True):
    var2 = tf.get_variable("var1",[],dtype=tf.float64)
    print(var2.name)

var1:0
var1:0


In [ ]:
#Tf reshape
# simulate batch of image patches
x = np.arange(3 * 2 * 8).reshape(3, 2, 4, 2, 1)

# reshape/ concat image patches along axis 3
x_new = tf.reshape(x, (3, 4, 4, 1))

In [ ]:
x_new

<tf.Tensor 'Reshape:0' shape=(3, 4, 4, 1) dtype=int64>

In [ ]:
print(x_new[0, :, :, 0])

Tensor("strided_slice_2:0", shape=(4, 4), dtype=int64)


In [ ]:
#Stworzyli sobie tensor2d o wymiarach 12x6 wyciagneli element 
#a. 4 od konca w ostatnim wierszu  
#b. drugi od początku w 3 wierszu 
#c. element środkowy
#Uzupełnić macierz samymi 10 z użyciem funkcji bibliotecznych i następnie zsumować jej elementy
#Stworzyć 3 zmienne przyjmujące jakąś wartość

# Tworzenie tensorów z funkcji bibliotecznych

In [ ]:
a = tf.ones((100,))
print(tfs.run(a))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [ ]:
c = tf.fill((2,2),2.)
d = tf.fill((2,2), 7.)
e= c*d
e.eval

<bound method Tensor.eval of <tf.Tensor 'mul_2:0' shape=(2, 2) dtype=float32>>

In [ ]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(e.eval())

[[14. 14.]
 [14. 14.]]


# Zamknięcie sesji interaktywnej

In [ ]:
tfs.close()

# Grafy obliczeniowe

## Budowa i uruchomienie prostego grafu obliczeniowego

In [ ]:
# Przyjmujemy model liniowy y = w * x + b
# Definiowanie parametrów modelu
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Definiowanie wejścia i wyjścia modelu
x = tf.placeholder(tf.float32)
y = w * x + b
output = 0

with tf.Session() as tfs:
    # Inicjacja i wydruk zmiennej y
    tf.global_variables_initializer().run()
    output = tfs.run(y, {x: [1, 2, 3, 4]})
print('wyjście : ', output)

wyjście :  [0.         0.3        0.6        0.90000004]


### Rozmieszczanie na CPU

In [ ]:
tf.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Definiowanie parametrów modelu
    w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
    b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
    # Definiowanie wejścia i wyjścia modelu
    x = tf.placeholder(name='x', dtype=tf.float32)
    y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # Inicjacja i wydruk zmiennej y
    tfs.run(tf.global_variables_initializer())
    print('wyjście', tfs.run(y, {x: [1, 2, 3, 4]}))

wyjście [0.         0.3        0.6        0.90000004]


## Wykonywanie grafu g jako domyślnego

In [ ]:
g = tf.Graph()
output = 0

# Przyjmujemy model liniowy y = w * x + b

with g.as_default():
    # Definiowanie parametrów modelu
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    # Definiowanie wejścia i wyjścia modelu
    x = tf.placeholder(tf.float32)
    y = w * x + b

with tf.Session(graph=g) as tfs:
    # Inicjacja i wydruk zmiennej y
    tf.global_variables_initializer().run()
    output = tfs.run(y, {x: [1, 2, 3, 4]})

print('wyjście : ', output)

wyjście :  [0.         0.3        0.6        0.90000004]


# Regresja logistyczna z TensorFlow

In [ ]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.examples.tutorials.mnist import input_data
print ("PACKAGES LOADED")

PACKAGES LOADED


In [ ]:
mnist      = input_data.read_data_sets('data/', one_hot=True)
trainimg   = mnist.train.images
trainlabel = mnist.train.labels
testimg    = mnist.test.images
testlabel  = mnist.test.labels
print ("MNIST loaded")

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
MN

In [ ]:
x = tf.placeholder("float", [None, 784]) 
y = tf.placeholder("float", [None, 10])  # None is for infinite 
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))
# LOGISTIC REGRESSION MODEL
actv = tf.nn.softmax(tf.matmul(x, W) + b) 
# COST FUNCTION
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(actv), reduction_indices=1)) 
# OPTIMIZER
learning_rate = 0.00001
optm = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [ ]:
# PREDICTION
pred = tf.equal(tf.argmax(actv, 1), tf.argmax(y, 1))    
# ACCURACY
accr = tf.reduce_mean(tf.cast(pred, "float"))
# INITIALIZER
init = tf.initialize_all_variables()

In [ ]:
training_epochs = 100
batch_size      = 100
display_step    = 10
# SESSION
sess = tf.Session()
sess.run(init)
# MINI-BATCH LEARNING
for epoch in range(training_epochs):
    avg_cost = 0.
    num_batch = int(mnist.train.num_examples/batch_size)
    for i in range(num_batch): 
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        sess.run(optm, feed_dict={x: batch_xs, y: batch_ys})
        feeds = {x: batch_xs, y: batch_ys}
        avg_cost += sess.run(cost, feed_dict=feeds)/num_batch
    # DISPLAY
    if epoch % display_step == 0:
        feeds_train = {x: batch_xs, y: batch_ys}
        feeds_test = {x: mnist.test.images, y: mnist.test.labels}
        train_acc = sess.run(accr, feed_dict=feeds_train)
        test_acc = sess.run(accr, feed_dict=feeds_test)
        print ("Epoch: %03d/%03d cost: %.9f train_acc: %.3f test_acc: %.3f" 
               % (epoch, training_epochs, avg_cost, train_acc, test_acc))
print ("DONE")

Epoch: 000/100 cost: 2.299604841 train_acc: 0.620 test_acc: 0.672
Epoch: 010/100 cost: 2.241755223 train_acc: 0.630 test_acc: 0.690
Epoch: 020/100 cost: 2.186685179 train_acc: 0.740 test_acc: 0.704
Epoch: 030/100 cost: 2.134059795 train_acc: 0.740 test_acc: 0.716
Epoch: 040/100 cost: 2.083842604 train_acc: 0.650 test_acc: 0.726
Epoch: 050/100 cost: 2.035540134 train_acc: 0.740 test_acc: 0.735
Epoch: 060/100 cost: 1.989186013 train_acc: 0.670 test_acc: 0.741
Epoch: 070/100 cost: 1.944767219 train_acc: 0.730 test_acc: 0.747
Epoch: 080/100 cost: 1.902213409 train_acc: 0.770 test_acc: 0.752
Epoch: 090/100 cost: 1.861308463 train_acc: 0.740 test_acc: 0.757
DONE
